branches:
  - main

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - - '@semantic-release/github'
    - assets:
        - path: release-artifacts/linux-x64-binary
          name: vrc-osc-manager
          label: Linux x64 binary
        - path: release-artifacts/windows-x64-binary
          name: vrc-osc-manager.exe
          label: Windows x64 binary
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
        - Cargo.toml
        - Cargo.lock
      message: "chore(release): set `Cargo.toml` to ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
