import { AppWindow, Router, UpdateNotice } from "app_window.slint";
import { PluginItem, PluginItems } from "pages/plugins.slint";
import { Settings } from "pages/settings.slint";
import { PishockSettings } from "plugins/pishock.slint";
import { MediaControlSettings } from "plugins/media_control.slint";

export {
    AppWindow,
    Router,
    UpdateNotice,
    PluginItem,
    PluginItems,
    Settings,
    PishockSettings,
    MediaControlSettings,
}
